name: Update streak stats

on:
  schedule:
    - cron: "0 3 * * *" # Runs daily at 03:00 UTC
  push:
    branches:
      - main
    paths:
      - ".github/workflows/streak.yml"
  workflow_dispatch: # Allows manual run

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate streak stats
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          options: user=archana1801&theme=tokyonight&border=00f2fe&background=0d1117&fire=ff007f&ring=00f2fe&currStreakLabel=00f2fe
          path: assets/streak.svg

      - name: Commit streak stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/streak.svg
          git commit -m "Update streak stats SVG" || exit 0
          git push
